export const projects = [
  {
    title: "Passports",
    creator: "Matthew Stanciu / ",
    creatorLink: "",
    description:
      "NFC-embedded booklets serving as the official ID of the Republic of Hackerland.",
    photo: "/img/passport.jpg",
    medium: "",
  },
  {
    title: "Phone Bell",
    creator: "Hazel Roeder",
    creatorLink: "",
    description: "Rotary phone-activated doorbell that doubles as an intercom.",
    photo: "/img/phone.jpg",
    medium: "",
  },
  {
    title: "The Sign",
    creator: "Jack Hogan / Hazel Roeder",
    creatorLink: "",
    description:
      "Meter-tall Conway glider that lights up according to Lightning Time (hexidecimal Purdue Hackers time unit).",
    photo: "/img/sign.jpg",
    medium: "",
  },
  {
    title: "ETea",
    creator: "Jadden / ",
    creatorLink: "",
    description: "Videogame.",
    photo: "/img/etea.jpg",
    medium: "",
  },
  {
    title: "Vine Script",
    creator: "Ayden Bridges",
    creatorLink: "",
    description: "script of vine.",
    photo: "/img/vine.jpg",
    medium: "",
  },
  {
    title: "Badges",
    creator: "Sean Choi / Every single other person who has made a badge",
    creatorLink: "",
    description: "Custom designed community tokens laser-cut every Hack Night.",
    photo: "",
    medium: "",
  },
  {
    title: "Door opener",
    creator: "Hazel Roeder",
    creatorLink: "",
    description: "Passport-activated door opener.",
    photo: "",
    medium: "",
  },
  {
    title: "Receipt printer",
    creator: "Hazel Roeder",
    creatorLink: "",
    description:
      "Receipt printers printing transcription of live gallery audio.",
    photo: "",
    medium: "",
  },
  {
    title: "keymashd",
    creator: "Kart",
    creatorLink: "",
    description: "Kart’s hackertyper packet loss installation",
    photo: "",
    medium: "",
  },
  {
    title: "",
    creator: "",
    creatorLink: "",
    description: "",
    photo: "",
    medium: "",
  },
];
